### ISSUE TITLE
Add test cases to check the 0 expiration

### ISSUE THREAD

**Issue by peterlimg** [0chain/system_test#143]
Add test cases to cover the changes on PR https://github.com/0chain/0chain/pull/816

**Comment by princeparmar** [comment]
@cnlangzi in zbox we have default handling for expiration. so we won't be able to create a failure case. to handle this properly we need to remove default handling from blobber.
https://github.com/0chain/zboxcli/blob/5ef3c03add0cb2080f356e54753977366e00ae93/cmd/newallocation.go#L241

**Comment by cnlangzi** [comment]
@princeparmar no, you are checking on wrong cmd. It is `share` on https://github.com/0chain/zboxcli/pull/131 . please help @Rizary  to fix test issues and got them(gosdk/zboxcli) merged first

**Comment by cnlangzi** [comment]
@stewartie4 could you ask some guy from system test team to get it done?

**Comment by stewartie4** [comment]
@cnlangzi were system tests not added to cover the new behaviour on the original PR? 
I'm on my phone so can't load it 
if not they should have been added at the time, I think we have a task to remind devs to do this but maybe not on all repos, i'll check when i get home

**Comment by stewartie4** [comment]
@cnlangzi yes no problem this time because it looks small but in general we can't write tests for every new dev change being merged, that needs to be the responsibility of the dev that wrote the new feature as they have the most context on how it should work

**Comment by Rizary** [comment]
I'm still working on it. Do you want me to stop and let your team fixed
this?

**Comment by cnlangzi** [comment]
@Rizary  glad to hear you are working on it. please go ahead.

**Comment by Naman-1234** [comment]
@Kishan-Dhakan @stewartie4 I have a doubt, In this issue I need to write test cases to check the zero expiry, But for this we first need to register and allocate it, But on allocating it with zero expiry, it gives the following error:

`
--- FAIL: TestShareFile (0.00s)                                                                                                                                                                                        --- FAIL: TestShareFile/Share_unencrypted_file_to_public_using_auth_ticket (45.91s)                                                                                                                                    zwalletcli_register_wallet_test.go:108: Registering wallet...                                                                                                                                                      zboxcli_update_allocation_test.go:588: Executing faucet...                                                                                                                                                         zboxcli_create_allocation_test.go:288: Creating new allocation...                                                                                                                                                  utils.go:62: Command failed on attempt [1/3] due to error [exit status 1]. Output: [Error creating allocation: allocation_creation_failed: invalid request: insufficient allocation duration]                      utils.go:62: Command failed on attempt [2/3] due to error [exit status 1]. Output: [Error creating allocation: allocation_creation_failed: invalid request: insufficient allocation duration]                      utils.go:65: Command failed on final attempt [3/3] due to error [exit status 1]. Command String: [./zbox newallocation --lock 0.5 --size 10485760 --expire 0 --parity 1 --data 1 --silent --wallet TestShareFile-Share_unencrypted_file_to_public_using_auth_ticket_wallet.json --configDir ./config --config ./zbox_config.yaml --allocationFileName TestShareFile-Share_unencrypted_file_to_public_using_auth_ticket_allocation.txt] Output: [Error creating allocation: allocation_creation_failed: invalid request: insufficient allocation duration]                                                                                                utils.go:68: The verbose output for the command is:                                                                                                                                                                utils.go:72: 0chain-core-sdk [INFO]   2022/08/27 18:56:36.632571 wallet_base.go:260: ******* Wallet SDK Version:v1.8.6-11-g09a231dc-dirty ******* (SetLogFile)                                                     utils.go:72: 0box-sdk        [INFO]   2022/08/27 18:56:36.633134 sdk.go:73: ******* Storage SDK Version: v1.8.6-11-g09a231dc-dirty *******                                                                         utils.go:72: 0chain-core-sdk [INFO]   2022/08/27 18:56:37.389805 transaction.go:1332: ******* Wallet SDK Version:v1.8.6-11-g09a231dc-dirty ******* (InitZCNSDK)                                                    utils.go:72: 0box-sdk        [DEBUG]  2022/08/27 18:56:38.000162 networkworker.go:105: Get network result:{"miners":["https://dev-2.devnet-0chain.net/miner02","https://dev-2.devnet-0chain.net/miner01","https://dev-2.devnet-0chain.net/miner03"],"sharders":["https://dev-2.devnet-0chain.net/sharder02","https://dev-2.devnet-0chain.net/sharder01"]}                                                                             utils.go:72: Error creating allocation: allocation_creation_failed: invalid request: insufficient allocation duration                                                                                              zboxcli_share_file_test.go:1579:                                                                                                                                                                                           Error Trace:    zboxcli_share_file_test.go:1579                                                                                                                                                                                                            zboxcli_share_file_test.go:82                                                                                                                                              Error:          Expected nil, but got: &exec.ExitError{ProcessState:(*os.ProcessState)(0xc0000b04b0), Stderr:[]uint8(nil)}                                                                                         Test:           TestShareFile/Share_unencrypted_file_to_public_using_auth_ticket                                                                                                                                   Messages:       Failed to create new allocation%!(EXTRA string=Error creating allocation: allocation_creation_failed: invalid request: insufficient allocation duration)                           FAIL                                                                                                                                                                                                               exit status 1                                                                                                                                                                                                      FAIL    github.com/0chain/system_test/tests/cli_tests   46.026s
`
