### ISSUE TITLE
System test for new atlus endpoints.

### ISSUE THREAD

**Issue by Sriep** [0chain/system_test#366]
20+ new REST API endpoints to support Atlus chimneys. This is for historic data for graphs and summary statistics.
Done in https://github.com/0chain/0chain/pull/1475.

**Comment by killbotXD** [comment]
@Sriep I was thinking of picking these tests up. should I split this ticket into 4 tickets based on the category of endpoints namely? 
-  global totals
- per blobber historic averaged metrics for graphs
- per blobber historic difference metric for graphs
- global historic metrics for graphs
since  there are around 30 endpoints actually

**Comment by Kishan-Dhakan** [comment]
@killbotXD yes that should be fine, after you splitting also close this issue.

**Comment by killbotXD** [comment]
Split this issue into #417 #418 #419 #420
